In [75]:
import duckdb
import polars as pl
from pathlib import Path

## Last.fm data

In [76]:
data_dir = Path("../data/lastfm/listening")
db = duckdb.read_json(data_dir/"*.jsonl")
df = db.pl()

df = df.with_columns(
    pl.from_epoch(
        pl.col("date_played_unix"), time_unit="s"
    ).alias("track_played_utc")
)
print("Raw data:", df.shape)

df = df.unique("date_played_unix") # Not so exact with which duplicate gets removed
print("Duplicate timestamps removed:", df.unique("date_played_unix").shape)
df.head()

Raw data: (110513, 8)
Duplicate timestamps removed: (108066, 8)

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ artist_nam ┆ artist_mbi ┆ album_name ┆ album_mbi ┆ track_nam ┆ track_mbi ┆ date_play ┆ track_pla │
│ e          ┆ d          ┆ ---        ┆ d         ┆ e         ┆ d         ┆ ed_unix   ┆ yed_utc   │
│ ---        ┆ ---        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆            ┆ str       ┆ str       ┆ str       ┆ i64       ┆ datetime[ │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ μs]       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Yung Lean  ┆            ┆ Frost God  ┆           ┆ Hennessy  ┆           ┆ 173947120 ┆ 2025-02-1 │
│            ┆            ┆            ┆           ┆ & Sailor  ┆           ┆ 9         ┆ 3         │
│            ┆            ┆            ┆           ┆ Moon      ┆           ┆           ┆ 18:26:49  │
│ Cynthoni   ┆ ef8dae4f-8 ┆ Sewerslvt  ┆ 2e902803- ┆ Lychee    ┆ ea05e66c- ┆ 172457500 ┆ 2024-08-2 │
│            ┆ b71-454f-a ┆ Presents:  ┆ 9553-4c37 ┆ Ice       ┆ 6664-445e ┆ 8         ┆ 5         │
│            ┆ d40-9f5370 ┆ Cynthoni,  ┆ -92f3-e0e ┆           ┆ -b7f2-bc4 ┆           ┆ 08:36:48  │
│            ┆ …          ┆ …          ┆ d26…      ┆           ┆ 6ad…      ┆           ┆           │
│ Dikke Baap ┆            ┆ IK TRIP 'M ┆           ┆ IK TRIP   ┆           ┆ 174697199 ┆ 2025-05-1 │
│            ┆            ┆ (Dimitri K ┆           ┆ 'M -      ┆           ┆ 4         ┆ 1         │
│            ┆            ┆ Remix)     ┆           ┆ Dimitri K ┆           ┆           ┆ 13:59:54  │
│            ┆            ┆            ┆           ┆ Remix     ┆           ┆           ┆           │
│ Pikekyss   ┆ 96180fc2-a ┆ Herregud   ┆           ┆ Herregud  ┆           ┆ 168630650 ┆ 2023-06-0 │
│            ┆ 8b6-466c-8 ┆            ┆           ┆           ┆           ┆ 7         ┆ 9         │
│            ┆ 6a7-b621ff ┆            ┆           ┆           ┆           ┆           ┆ 10:28:27  │
│            ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ TØFL       ┆ 21a3df18-4 ┆ Alle Andre ┆           ┆ Alle      ┆ af5abc9a- ┆ 164659057 ┆ 2022-03-0 │
│            ┆ cb5-478f-8 ┆ Får Lov    ┆           ┆ andre får ┆ 1a51-445b ┆ 7         ┆ 6         │
│            ┆ 955-fdcfb4 ┆            ┆           ┆ lov       ┆ -838b-c6c ┆           ┆ 18:16:17  │
│            ┆ …          ┆            ┆           ┆           ┆ be3…      ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [77]:
df.filter(pl.col("artist_name").is_null())

shape: (17, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ artist_nam ┆ artist_mbi ┆ album_name ┆ album_mbi ┆ track_nam ┆ track_mbi ┆ date_play ┆ track_pla │
│ e          ┆ d          ┆ ---        ┆ d         ┆ e         ┆ d         ┆ ed_unix   ┆ yed_utc   │
│ ---        ┆ ---        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆            ┆ str       ┆ str       ┆ str       ┆ i64       ┆ datetime[ │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ μs]       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ null       ┆            ┆ null       ┆           ┆ null      ┆           ┆ 174048406 ┆ 2025-02-2 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 1         ┆ 5         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 11:47:41  │
│ null       ┆            ┆ null       ┆           ┆ null      ┆           ┆ 174050704 ┆ 2025-02-2 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 6         ┆ 5         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 18:10:46  │
│ null       ┆            ┆ null       ┆           ┆ null      ┆           ┆ 174015995 ┆ 2025-02-2 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 7         ┆ 1         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 17:45:57  │
│ null       ┆            ┆ null       ┆           ┆ null      ┆           ┆ 174059054 ┆ 2025-02-2 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 7         ┆ 6         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 17:22:27  │
│ null       ┆            ┆ null       ┆           ┆ null      ┆           ┆ 174055890 ┆ 2025-02-2 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 5         ┆ 6         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 08:35:05  │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ null       ┆            ┆ null       ┆           ┆ null      ┆           ┆ 174058055 ┆ 2025-02-2 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 4         ┆ 6         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 14:35:54  │
│ null       ┆            ┆ null       ┆           ┆ null      ┆           ┆ 174051986 ┆ 2025-02-2 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 8         ┆ 5         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 21:44:28  │
│ null       ┆            ┆ null       ┆           ┆ null      ┆           ┆ 174050647 ┆ 2025-02-2 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 9         ┆ 5         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 18:01:19  │
│ null       ┆            ┆ null       ┆           ┆ null      ┆           ┆ 174082146 ┆ 2025-03-0 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 4         ┆ 1         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 09:31:04  │
│ null       ┆            ┆ null       ┆           ┆ null      ┆           ┆ 174050786 ┆ 2025-02-2 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 4         ┆ 5         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 18:24:24  │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [78]:
earliest_timestamp = df.select(pl.col("date_played_unix").min()).item()
earliest_timestamp

1621491935

## Spotify data

In [79]:
spotify_dir = Path("../data/spotify")
spotify_db = duckdb.read_json(spotify_dir/"extended streaming history/*.json")
spotify_df = spotify_db.pl()
spotify_df.head()

shape: (5, 23)
┌────────────┬────────────┬───────────┬────────────┬───┬─────────┬─────────┬───────────┬───────────┐
│ ts         ┆ platform   ┆ ms_played ┆ conn_count ┆ … ┆ skipped ┆ offline ┆ offline_t ┆ incognito │
│ ---        ┆ ---        ┆ ---       ┆ ry         ┆   ┆ ---     ┆ ---     ┆ imestamp  ┆ _mode     │
│ datetime[μ ┆ str        ┆ i64       ┆ ---        ┆   ┆ bool    ┆ bool    ┆ ---       ┆ ---       │
│ s]         ┆            ┆           ┆ str        ┆   ┆         ┆         ┆ i64       ┆ bool      │
╞════════════╪════════════╪═══════════╪════════════╪═══╪═════════╪═════════╪═══════════╪═══════════╡
│ 2017-12-17 ┆ Partner    ┆ 216391    ┆ ZZ         ┆ … ┆ false   ┆ false   ┆ null      ┆ false     │
│ 10:31:16   ┆ spotify    ┆           ┆            ┆   ┆         ┆         ┆           ┆           │
│            ┆ web_player ┆           ┆            ┆   ┆         ┆         ┆           ┆           │
│ 2017-12-17 ┆ Partner    ┆ 210942    ┆ ZZ         ┆ … ┆ false   ┆ false   ┆ null      ┆ false     │
│ 10:34:47   ┆ spotify    ┆           ┆            ┆   ┆         ┆         ┆           ┆           │
│            ┆ web_player ┆           ┆            ┆   ┆         ┆         ┆           ┆           │
│ 2017-12-17 ┆ Partner    ┆ 236946    ┆ ZZ         ┆ … ┆ false   ┆ false   ┆ null      ┆ false     │
│ 10:38:45   ┆ spotify    ┆           ┆            ┆   ┆         ┆         ┆           ┆           │
│            ┆ web_player ┆           ┆            ┆   ┆         ┆         ┆           ┆           │
│ 2017-12-17 ┆ Partner    ┆ 189949    ┆ ZZ         ┆ … ┆ false   ┆ false   ┆ null      ┆ false     │
│ 10:41:56   ┆ spotify    ┆           ┆            ┆   ┆         ┆         ┆           ┆           │
│            ┆ web_player ┆           ┆            ┆   ┆         ┆         ┆           ┆           │
│ 2017-12-17 ┆ Partner    ┆ 63316     ┆ ZZ         ┆ … ┆ false   ┆ false   ┆ null      ┆ false     │
│ 10:43:01   ┆ spotify    ┆           ┆            ┆   ┆         ┆         ┆           ┆           │
│            ┆ web_player ┆           ┆            ┆   ┆         ┆         ┆           ┆           │
└────────────┴────────────┴───────────┴────────────┴───┴─────────┴─────────┴───────────┴───────────┘

In [80]:
columns_of_interest = [
    "ts",
    "ms_played",
    "master_metadata_track_name",
    "master_metadata_album_artist_name",
    "master_metadata_album_album_name",
    "offline_timestamp",
    "spotify_track_uri"
]

new_col_names = {
    'ts': "track_played_utc",
    'master_metadata_track_name': "track_name",
    'master_metadata_album_artist_name': "artist_name",
    'master_metadata_album_album_name': "album_name",
    'offline_timestamp': "date_played_unix",
}

spotify_df = (
    spotify_df
    .select(columns_of_interest)
    .rename(new_col_names)
)
spotify_df

shape: (401_505, 7)
┌──────────────┬───────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┐
│ track_played ┆ ms_played ┆ track_name   ┆ artist_name  ┆ album_name  ┆ date_played ┆ spotify_tra │
│ _utc         ┆ ---       ┆ ---          ┆ ---          ┆ ---         ┆ _unix       ┆ ck_uri      │
│ ---          ┆ i64       ┆ str          ┆ str          ┆ str         ┆ ---         ┆ ---         │
│ datetime[μs] ┆           ┆              ┆              ┆             ┆ i64         ┆ str         │
╞══════════════╪═══════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 2017-12-17   ┆ 216391    ┆ Like A G6    ┆ Far East     ┆ Free Wired  ┆ null        ┆ spotify:tra │
│ 10:31:16     ┆           ┆              ┆ Movement     ┆             ┆             ┆ ck:5AyL2kgL │
│              ┆           ┆              ┆              ┆             ┆             ┆ tTWEu3qO…   │
│ 2017-12-17   ┆ 210942    ┆ Rocketeer    ┆ Far East     ┆ Free Wired  ┆ null        ┆ spotify:tra │
│ 10:34:47     ┆           ┆              ┆ Movement     ┆             ┆             ┆ ck:3ZuiIFm9 │
│              ┆           ┆              ┆              ┆             ┆             ┆ nRnkRz8A…   │
│ 2017-12-17   ┆ 236946    ┆ Live My Life ┆ Far East     ┆ Dirty Bass  ┆ null        ┆ spotify:tra │
│ 10:38:45     ┆           ┆              ┆ Movement     ┆             ┆             ┆ ck:6dpKQiQz │
│              ┆           ┆              ┆              ┆             ┆             ┆ ZE2r9rZV…   │
│ 2017-12-17   ┆ 189949    ┆ Freal Luv    ┆ Far East     ┆ Freal Luv   ┆ null        ┆ spotify:tra │
│ 10:41:56     ┆           ┆ (feat.       ┆ Movement     ┆ (feat.      ┆             ┆ ck:00rbUJGb │
│              ┆           ┆ Chanyeol &   ┆              ┆ Chanyeol &  ┆             ┆ cjw3FW5c…   │
│              ┆           ┆ Ti…          ┆              ┆ Ti…         ┆             ┆             │
│ 2017-12-17   ┆ 63316     ┆ Turn Up The  ┆ Far East     ┆ Dirty Bass  ┆ null        ┆ spotify:tra │
│ 10:43:01     ┆           ┆ Love         ┆ Movement     ┆             ┆             ┆ ck:4HQ9gXAt │
│              ┆           ┆              ┆              ┆             ┆             ┆ ONKs8NCM…   │
│ …            ┆ …         ┆ …            ┆ …            ┆ …           ┆ …           ┆ …           │
│ 2025-09-29   ┆ 671       ┆ Love Takes   ┆ Cameron      ┆ Love Takes  ┆ null        ┆ spotify:tra │
│ 07:56:14     ┆           ┆ Miles        ┆ Winter       ┆ Miles       ┆             ┆ ck:48cPTTDc │
│              ┆           ┆              ┆              ┆             ┆             ┆ Zz6PRE1k…   │
│ 2025-09-29   ┆ 20810     ┆ take me by   ┆ Oklou        ┆ take me by  ┆ 1759158304  ┆ spotify:tra │
│ 15:05:25     ┆           ┆ the hand     ┆              ┆ the hand    ┆             ┆ ck:0nuH0iso │
│              ┆           ┆ (feat. Bla…  ┆              ┆ (feat. Bla… ┆             ┆ VlLDIRk3…   │
│ 2025-10-01   ┆ 5200      ┆ The Coward   ┆ Chanel Beads ┆ The Coward  ┆ 1759301009  ┆ spotify:tra │
│ 06:43:34     ┆           ┆ Forgets His  ┆              ┆ Forgets His ┆             ┆ ck:3LItdxCk │
│              ┆           ┆ Nightma…     ┆              ┆ Nightma…    ┆             ┆ ntoyFyoh…   │
│ 2025-10-01   ┆ 1080      ┆ The Coward   ┆ Chanel Beads ┆ The Coward  ┆ 1759333209  ┆ spotify:tra │
│ 15:40:11     ┆           ┆ Forgets His  ┆              ┆ Forgets His ┆             ┆ ck:3LItdxCk │
│              ┆           ┆ Nightma…     ┆              ┆ Nightma…    ┆             ┆ ntoyFyoh…   │
│ 2025-10-01   ┆ 1810      ┆ The Coward   ┆ Chanel Beads ┆ The Coward  ┆ 1759336070  ┆ spotify:tra │
│ 16:27:53     ┆           ┆ Forgets His  ┆              ┆ Forgets His ┆             ┆ ck:3LItdxCk │
│              ┆           ┆ Nightma…     ┆              ┆ Nightma…    ┆             ┆ ntoyFyoh…   │
└──────────────┴───────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┘

In [81]:
# From the resulting dataframe I see that there may be null-values. Lets investigate further.
spotify_df.null_count()

shape: (1, 7)
┌───────────────┬───────────┬────────────┬─────────────┬────────────┬───────────────┬──────────────┐
│ track_played_ ┆ ms_played ┆ track_name ┆ artist_name ┆ album_name ┆ date_played_u ┆ spotify_trac │
│ utc           ┆ ---       ┆ ---        ┆ ---         ┆ ---        ┆ nix           ┆ k_uri        │
│ ---           ┆ u32       ┆ u32        ┆ u32         ┆ u32        ┆ ---           ┆ ---          │
│ u32           ┆           ┆            ┆             ┆            ┆ u32           ┆ u32          │
╞═══════════════╪═══════════╪════════════╪═════════════╪════════════╪═══════════════╪══════════════╡
│ 0             ┆ 0         ┆ 4967       ┆ 4967        ┆ 4967       ┆ 220564        ┆ 4967         │
└───────────────┴───────────┴────────────┴─────────────┴────────────┴───────────────┴──────────────┘

Consistent missing values across 4 out of 7 which indicate some systemic pattern.

`date_played_unix` missing timestamps is not a problem as we can use 
`track_played_utc` to get the UNIX-timestamps.

In [82]:
spotify_df.filter(pl.col("track_name").is_null())

shape: (4_967, 7)
┌───────────────┬───────────┬────────────┬─────────────┬────────────┬───────────────┬──────────────┐
│ track_played_ ┆ ms_played ┆ track_name ┆ artist_name ┆ album_name ┆ date_played_u ┆ spotify_trac │
│ utc           ┆ ---       ┆ ---        ┆ ---         ┆ ---        ┆ nix           ┆ k_uri        │
│ ---           ┆ i64       ┆ str        ┆ str         ┆ str        ┆ ---           ┆ ---          │
│ datetime[μs]  ┆           ┆            ┆             ┆            ┆ i64           ┆ str          │
╞═══════════════╪═══════════╪════════════╪═════════════╪════════════╪═══════════════╪══════════════╡
│ 2018-03-29    ┆ 708162    ┆ null       ┆ null        ┆ null       ┆ null          ┆ null         │
│ 19:01:25      ┆           ┆            ┆             ┆            ┆               ┆              │
│ 2018-05-31    ┆ 1384536   ┆ null       ┆ null        ┆ null       ┆ null          ┆ null         │
│ 11:19:20      ┆           ┆            ┆             ┆            ┆               ┆              │
│ 2018-08-17    ┆ 2340000   ┆ null       ┆ null        ┆ null       ┆ null          ┆ null         │
│ 16:46:03      ┆           ┆            ┆             ┆            ┆               ┆              │
│ 2019-10-09    ┆ 1314017   ┆ null       ┆ null        ┆ null       ┆ null          ┆ null         │
│ 15:28:12      ┆           ┆            ┆             ┆            ┆               ┆              │
│ 2019-10-09    ┆ 4200      ┆ null       ┆ null        ┆ null       ┆ null          ┆ null         │
│ 17:45:42      ┆           ┆            ┆             ┆            ┆               ┆              │
│ …             ┆ …         ┆ …          ┆ …           ┆ …          ┆ …             ┆ …            │
│ 2025-06-10    ┆ 0         ┆ null       ┆ null        ┆ null       ┆ 1749559469    ┆ null         │
│ 12:44:29      ┆           ┆            ┆             ┆            ┆               ┆              │
│ 2025-06-10    ┆ 2090      ┆ null       ┆ null        ┆ null       ┆ 1749562540    ┆ null         │
│ 13:35:43      ┆           ┆            ┆             ┆            ┆               ┆              │
│ 2025-06-10    ┆ 60        ┆ null       ┆ null        ┆ null       ┆ 1749562550    ┆ null         │
│ 13:35:50      ┆           ┆            ┆             ┆            ┆               ┆              │
│ 2025-06-10    ┆ 0         ┆ null       ┆ null        ┆ null       ┆ 1749576811    ┆ null         │
│ 17:33:31      ┆           ┆            ┆             ┆            ┆               ┆              │
│ 2025-07-22    ┆ 0         ┆ null       ┆ null        ┆ null       ┆ 1753216820    ┆ null         │
│ 20:40:20      ┆           ┆            ┆             ┆            ┆               ┆              │
└───────────────┴───────────┴────────────┴─────────────┴────────────┴───────────────┴──────────────┘

In [83]:
spotify_df = spotify_df.filter(pl.col("track_name").is_not_null())
spotify_df

shape: (396_538, 7)
┌──────────────┬───────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┐
│ track_played ┆ ms_played ┆ track_name   ┆ artist_name  ┆ album_name  ┆ date_played ┆ spotify_tra │
│ _utc         ┆ ---       ┆ ---          ┆ ---          ┆ ---         ┆ _unix       ┆ ck_uri      │
│ ---          ┆ i64       ┆ str          ┆ str          ┆ str         ┆ ---         ┆ ---         │
│ datetime[μs] ┆           ┆              ┆              ┆             ┆ i64         ┆ str         │
╞══════════════╪═══════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 2017-12-17   ┆ 216391    ┆ Like A G6    ┆ Far East     ┆ Free Wired  ┆ null        ┆ spotify:tra │
│ 10:31:16     ┆           ┆              ┆ Movement     ┆             ┆             ┆ ck:5AyL2kgL │
│              ┆           ┆              ┆              ┆             ┆             ┆ tTWEu3qO…   │
│ 2017-12-17   ┆ 210942    ┆ Rocketeer    ┆ Far East     ┆ Free Wired  ┆ null        ┆ spotify:tra │
│ 10:34:47     ┆           ┆              ┆ Movement     ┆             ┆             ┆ ck:3ZuiIFm9 │
│              ┆           ┆              ┆              ┆             ┆             ┆ nRnkRz8A…   │
│ 2017-12-17   ┆ 236946    ┆ Live My Life ┆ Far East     ┆ Dirty Bass  ┆ null        ┆ spotify:tra │
│ 10:38:45     ┆           ┆              ┆ Movement     ┆             ┆             ┆ ck:6dpKQiQz │
│              ┆           ┆              ┆              ┆             ┆             ┆ ZE2r9rZV…   │
│ 2017-12-17   ┆ 189949    ┆ Freal Luv    ┆ Far East     ┆ Freal Luv   ┆ null        ┆ spotify:tra │
│ 10:41:56     ┆           ┆ (feat.       ┆ Movement     ┆ (feat.      ┆             ┆ ck:00rbUJGb │
│              ┆           ┆ Chanyeol &   ┆              ┆ Chanyeol &  ┆             ┆ cjw3FW5c…   │
│              ┆           ┆ Ti…          ┆              ┆ Ti…         ┆             ┆             │
│ 2017-12-17   ┆ 63316     ┆ Turn Up The  ┆ Far East     ┆ Dirty Bass  ┆ null        ┆ spotify:tra │
│ 10:43:01     ┆           ┆ Love         ┆ Movement     ┆             ┆             ┆ ck:4HQ9gXAt │
│              ┆           ┆              ┆              ┆             ┆             ┆ ONKs8NCM…   │
│ …            ┆ …         ┆ …            ┆ …            ┆ …           ┆ …           ┆ …           │
│ 2025-09-29   ┆ 671       ┆ Love Takes   ┆ Cameron      ┆ Love Takes  ┆ null        ┆ spotify:tra │
│ 07:56:14     ┆           ┆ Miles        ┆ Winter       ┆ Miles       ┆             ┆ ck:48cPTTDc │
│              ┆           ┆              ┆              ┆             ┆             ┆ Zz6PRE1k…   │
│ 2025-09-29   ┆ 20810     ┆ take me by   ┆ Oklou        ┆ take me by  ┆ 1759158304  ┆ spotify:tra │
│ 15:05:25     ┆           ┆ the hand     ┆              ┆ the hand    ┆             ┆ ck:0nuH0iso │
│              ┆           ┆ (feat. Bla…  ┆              ┆ (feat. Bla… ┆             ┆ VlLDIRk3…   │
│ 2025-10-01   ┆ 5200      ┆ The Coward   ┆ Chanel Beads ┆ The Coward  ┆ 1759301009  ┆ spotify:tra │
│ 06:43:34     ┆           ┆ Forgets His  ┆              ┆ Forgets His ┆             ┆ ck:3LItdxCk │
│              ┆           ┆ Nightma…     ┆              ┆ Nightma…    ┆             ┆ ntoyFyoh…   │
│ 2025-10-01   ┆ 1080      ┆ The Coward   ┆ Chanel Beads ┆ The Coward  ┆ 1759333209  ┆ spotify:tra │
│ 15:40:11     ┆           ┆ Forgets His  ┆              ┆ Forgets His ┆             ┆ ck:3LItdxCk │
│              ┆           ┆ Nightma…     ┆              ┆ Nightma…    ┆             ┆ ntoyFyoh…   │
│ 2025-10-01   ┆ 1810      ┆ The Coward   ┆ Chanel Beads ┆ The Coward  ┆ 1759336070  ┆ spotify:tra │
│ 16:27:53     ┆           ┆ Forgets His  ┆              ┆ Forgets His ┆             ┆ ck:3LItdxCk │
│              ┆           ┆ Nightma…     ┆              ┆ Nightma…    ┆             ┆ ntoyFyoh…   │
└──────────────┴───────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┘

In [84]:
# Filling in missing timestamps using 'date_played_unix'
spotify_df = ( 
    spotify_df
    .with_columns(
        date_played_unix = pl.col("date_played_unix").fill_null(
            pl.col("track_played_utc").dt.strftime("%s").cast(int)
        )
    )
)
spotify_df

shape: (396_538, 7)
┌──────────────┬───────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┐
│ track_played ┆ ms_played ┆ track_name   ┆ artist_name  ┆ album_name  ┆ date_played ┆ spotify_tra │
│ _utc         ┆ ---       ┆ ---          ┆ ---          ┆ ---         ┆ _unix       ┆ ck_uri      │
│ ---          ┆ i64       ┆ str          ┆ str          ┆ str         ┆ ---         ┆ ---         │
│ datetime[μs] ┆           ┆              ┆              ┆             ┆ i64         ┆ str         │
╞══════════════╪═══════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 2017-12-17   ┆ 216391    ┆ Like A G6    ┆ Far East     ┆ Free Wired  ┆ 1513506676  ┆ spotify:tra │
│ 10:31:16     ┆           ┆              ┆ Movement     ┆             ┆             ┆ ck:5AyL2kgL │
│              ┆           ┆              ┆              ┆             ┆             ┆ tTWEu3qO…   │
│ 2017-12-17   ┆ 210942    ┆ Rocketeer    ┆ Far East     ┆ Free Wired  ┆ 1513506887  ┆ spotify:tra │
│ 10:34:47     ┆           ┆              ┆ Movement     ┆             ┆             ┆ ck:3ZuiIFm9 │
│              ┆           ┆              ┆              ┆             ┆             ┆ nRnkRz8A…   │
│ 2017-12-17   ┆ 236946    ┆ Live My Life ┆ Far East     ┆ Dirty Bass  ┆ 1513507125  ┆ spotify:tra │
│ 10:38:45     ┆           ┆              ┆ Movement     ┆             ┆             ┆ ck:6dpKQiQz │
│              ┆           ┆              ┆              ┆             ┆             ┆ ZE2r9rZV…   │
│ 2017-12-17   ┆ 189949    ┆ Freal Luv    ┆ Far East     ┆ Freal Luv   ┆ 1513507316  ┆ spotify:tra │
│ 10:41:56     ┆           ┆ (feat.       ┆ Movement     ┆ (feat.      ┆             ┆ ck:00rbUJGb │
│              ┆           ┆ Chanyeol &   ┆              ┆ Chanyeol &  ┆             ┆ cjw3FW5c…   │
│              ┆           ┆ Ti…          ┆              ┆ Ti…         ┆             ┆             │
│ 2017-12-17   ┆ 63316     ┆ Turn Up The  ┆ Far East     ┆ Dirty Bass  ┆ 1513507381  ┆ spotify:tra │
│ 10:43:01     ┆           ┆ Love         ┆ Movement     ┆             ┆             ┆ ck:4HQ9gXAt │
│              ┆           ┆              ┆              ┆             ┆             ┆ ONKs8NCM…   │
│ …            ┆ …         ┆ …            ┆ …            ┆ …           ┆ …           ┆ …           │
│ 2025-09-29   ┆ 671       ┆ Love Takes   ┆ Cameron      ┆ Love Takes  ┆ 1759132574  ┆ spotify:tra │
│ 07:56:14     ┆           ┆ Miles        ┆ Winter       ┆ Miles       ┆             ┆ ck:48cPTTDc │
│              ┆           ┆              ┆              ┆             ┆             ┆ Zz6PRE1k…   │
│ 2025-09-29   ┆ 20810     ┆ take me by   ┆ Oklou        ┆ take me by  ┆ 1759158304  ┆ spotify:tra │
│ 15:05:25     ┆           ┆ the hand     ┆              ┆ the hand    ┆             ┆ ck:0nuH0iso │
│              ┆           ┆ (feat. Bla…  ┆              ┆ (feat. Bla… ┆             ┆ VlLDIRk3…   │
│ 2025-10-01   ┆ 5200      ┆ The Coward   ┆ Chanel Beads ┆ The Coward  ┆ 1759301009  ┆ spotify:tra │
│ 06:43:34     ┆           ┆ Forgets His  ┆              ┆ Forgets His ┆             ┆ ck:3LItdxCk │
│              ┆           ┆ Nightma…     ┆              ┆ Nightma…    ┆             ┆ ntoyFyoh…   │
│ 2025-10-01   ┆ 1080      ┆ The Coward   ┆ Chanel Beads ┆ The Coward  ┆ 1759333209  ┆ spotify:tra │
│ 15:40:11     ┆           ┆ Forgets His  ┆              ┆ Forgets His ┆             ┆ ck:3LItdxCk │
│              ┆           ┆ Nightma…     ┆              ┆ Nightma…    ┆             ┆ ntoyFyoh…   │
│ 2025-10-01   ┆ 1810      ┆ The Coward   ┆ Chanel Beads ┆ The Coward  ┆ 1759336070  ┆ spotify:tra │
│ 16:27:53     ┆           ┆ Forgets His  ┆              ┆ Forgets His ┆             ┆ ck:3LItdxCk │
│              ┆           ┆ Nightma…     ┆              ┆ Nightma…    ┆             ┆ ntoyFyoh…   │
└──────────────┴───────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┘

In [85]:
# Filter the dataset to the time range of interest.
# Then apply a filter to keep "valid scrobbles", as the exported dataset
# tracks any song played regardless of duration played.
spotify_df = ( 
    spotify_df
    .filter(pl.col("date_played_unix") < earliest_timestamp) 
    .filter(pl.col("ms_played") >= 30000)
    .drop(pl.col("ms_played"))
)
spotify_df

shape: (72_476, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ track_played_u ┆ track_name     ┆ artist_name    ┆ album_name    ┆ date_played_u ┆ spotify_track │
│ tc             ┆ ---            ┆ ---            ┆ ---           ┆ nix           ┆ _uri          │
│ ---            ┆ str            ┆ str            ┆ str           ┆ ---           ┆ ---           │
│ datetime[μs]   ┆                ┆                ┆               ┆ i64           ┆ str           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 2017-12-17     ┆ Like A G6      ┆ Far East       ┆ Free Wired    ┆ 1513506676    ┆ spotify:track │
│ 10:31:16       ┆                ┆ Movement       ┆               ┆               ┆ :5AyL2kgLtTWE │
│                ┆                ┆                ┆               ┆               ┆ u3qO…         │
│ 2017-12-17     ┆ Rocketeer      ┆ Far East       ┆ Free Wired    ┆ 1513506887    ┆ spotify:track │
│ 10:34:47       ┆                ┆ Movement       ┆               ┆               ┆ :3ZuiIFm9nRnk │
│                ┆                ┆                ┆               ┆               ┆ Rz8A…         │
│ 2017-12-17     ┆ Live My Life   ┆ Far East       ┆ Dirty Bass    ┆ 1513507125    ┆ spotify:track │
│ 10:38:45       ┆                ┆ Movement       ┆               ┆               ┆ :6dpKQiQzZE2r │
│                ┆                ┆                ┆               ┆               ┆ 9rZV…         │
│ 2017-12-17     ┆ Freal Luv      ┆ Far East       ┆ Freal Luv     ┆ 1513507316    ┆ spotify:track │
│ 10:41:56       ┆ (feat.         ┆ Movement       ┆ (feat.        ┆               ┆ :00rbUJGbcjw3 │
│                ┆ Chanyeol & Ti… ┆                ┆ Chanyeol &    ┆               ┆ FW5c…         │
│                ┆                ┆                ┆ Ti…           ┆               ┆               │
│ 2017-12-17     ┆ Turn Up The    ┆ Far East       ┆ Dirty Bass    ┆ 1513507381    ┆ spotify:track │
│ 10:43:01       ┆ Love           ┆ Movement       ┆               ┆               ┆ :4HQ9gXAtONKs │
│                ┆                ┆                ┆               ┆               ┆ 8NCM…         │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ 2021-05-20     ┆ Xcxoplex (with ┆ A. G. Cook     ┆ Xcxoplex      ┆ 1621491102    ┆ spotify:track │
│ 06:11:42       ┆ Charli XCX)    ┆                ┆ (with Charli  ┆               ┆ :3Qtc8RGzuzbD │
│                ┆                ┆                ┆ XCX)          ┆               ┆ GBpZ…         │
│ 2021-05-20     ┆ Miss The Rage  ┆ Trippie Redd   ┆ Miss The Rage ┆ 1621491339    ┆ spotify:track │
│ 06:15:39       ┆ (feat. Playboi ┆                ┆ (feat.        ┆               ┆ :2BITQ360Knh6 │
│                ┆ C…             ┆                ┆ Playboi C…    ┆               ┆ qNAO…         │
│ 2021-05-20     ┆ The Kiss Of    ┆ Paul McCartney ┆ McCartney III ┆ 1621491483    ┆ spotify:track │
│ 06:18:03       ┆ Venus (Dominic ┆                ┆ Imagined      ┆               ┆ :28kOGtTZzbfQ │
│                ┆ Fik…           ┆                ┆               ┆               ┆ 8fMm…         │
│ 2021-05-20     ┆ Sugar          ┆ Bladee         ┆ Eversince     ┆ 1621491670    ┆ spotify:track │
│ 06:21:10       ┆                ┆                ┆               ┆               ┆ :15lAXvjPkKhk │
│                ┆                ┆                ┆               ┆               ┆ qpgP…         │
│ 2021-05-20     ┆ dead cat       ┆ Teen Suicide   ┆ i will be my  ┆ 1621491788    ┆ spotify:track │
│ 06:23:08       ┆                ┆                ┆ own hell      ┆               ┆ :0GH60OOXzYfU │
│                ┆                ┆                ┆ because …     ┆               ┆ lTUw…         │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [86]:
# Time to export the data 
from pathlib import Path

dir_path = Path("../data/spotify")
spotify_df.write_parquet(dir_path/"2017-2021 spotify data.parquet")

## Vstack attempt

In [69]:
spotify_df.head()

shape: (5, 6)
┌─────────────────┬─────────────────┬─────────────┬────────────┬─────────────────┬─────────────────┐
│ track_played_ut ┆ track_name      ┆ artist_name ┆ album_name ┆ date_played_uni ┆ spotify_track_u │
│ c               ┆ ---             ┆ ---         ┆ ---        ┆ x               ┆ ri              │
│ ---             ┆ str             ┆ str         ┆ str        ┆ ---             ┆ ---             │
│ datetime[μs]    ┆                 ┆             ┆            ┆ i64             ┆ str             │
╞═════════════════╪═════════════════╪═════════════╪════════════╪═════════════════╪═════════════════╡
│ 2017-12-17      ┆ Like A G6       ┆ Far East    ┆ Free Wired ┆ 1513506676      ┆ spotify:track:5 │
│ 10:31:16        ┆                 ┆ Movement    ┆            ┆                 ┆ AyL2kgLtTWEu3qO │
│                 ┆                 ┆             ┆            ┆                 ┆ …               │
│ 2017-12-17      ┆ Rocketeer       ┆ Far East    ┆ Free Wired ┆ 1513506887      ┆ spotify:track:3 │
│ 10:34:47        ┆                 ┆ Movement    ┆            ┆                 ┆ ZuiIFm9nRnkRz8A │
│                 ┆                 ┆             ┆            ┆                 ┆ …               │
│ 2017-12-17      ┆ Live My Life    ┆ Far East    ┆ Dirty Bass ┆ 1513507125      ┆ spotify:track:6 │
│ 10:38:45        ┆                 ┆ Movement    ┆            ┆                 ┆ dpKQiQzZE2r9rZV │
│                 ┆                 ┆             ┆            ┆                 ┆ …               │
│ 2017-12-17      ┆ Freal Luv       ┆ Far East    ┆ Freal Luv  ┆ 1513507316      ┆ spotify:track:0 │
│ 10:41:56        ┆ (feat. Chanyeol ┆ Movement    ┆ (feat.     ┆                 ┆ 0rbUJGbcjw3FW5c │
│                 ┆ & Ti…           ┆             ┆ Chanyeol & ┆                 ┆ …               │
│                 ┆                 ┆             ┆ Ti…        ┆                 ┆                 │
│ 2017-12-17      ┆ Turn Up The     ┆ Far East    ┆ Dirty Bass ┆ 1513507381      ┆ spotify:track:4 │
│ 10:43:01        ┆ Love            ┆ Movement    ┆            ┆                 ┆ HQ9gXAtONKs8NCM │
│                 ┆                 ┆             ┆            ┆                 ┆ …               │
└─────────────────┴─────────────────┴─────────────┴────────────┴─────────────────┴─────────────────┘

In [93]:
set(spotify_df.columns + df.columns)

{'album_mbid',
 'album_name',
 'artist_mbid',
 'artist_name',
 'date_played_unix',
 'spotify_track_uri',
 'track_mbid',
 'track_name',
 'track_played_utc'}

In [92]:
sorted(spotify_df.columns)

['album_name',
 'artist_name',
 'date_played_unix',
 'spotify_track_uri',
 'track_name',
 'track_played_utc']

In [70]:
spotify_df = spotify_df.with_columns(
    artist_mbid = pl.lit(""),
    album_mbid = pl.lit(""),
    track_mbid = pl.lit("")
)

In [71]:
df.head()

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ artist_nam ┆ artist_mbi ┆ album_name ┆ album_mbi ┆ track_nam ┆ track_mbi ┆ date_play ┆ track_pla │
│ e          ┆ d          ┆ ---        ┆ d         ┆ e         ┆ d         ┆ ed_unix   ┆ yed_utc   │
│ ---        ┆ ---        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆            ┆ str       ┆ str       ┆ str       ┆ i64       ┆ datetime[ │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ μs]       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Target Dem ┆            ┆ Dreaming   ┆           ┆ Dreaming  ┆           ┆ 173754811 ┆ 2025-01-2 │
│ ographic   ┆            ┆ About You  ┆           ┆ About You ┆           ┆ 7         ┆ 2         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 12:15:17  │
│ Tyler, The ┆            ┆ IGOR       ┆           ┆ I THINK   ┆           ┆ 173892341 ┆ 2025-02-0 │
│ Creator    ┆            ┆            ┆           ┆           ┆           ┆ 2         ┆ 7         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 10:16:52  │
│ Frank      ┆ e520459c-d ┆ Blonde     ┆ 08f54f68- ┆ Solo      ┆ 8682b979- ┆ 166936561 ┆ 2022-11-2 │
│ Ocean      ┆ ff4-491d-a ┆            ┆ 7c89-4e22 ┆ (Reprise) ┆ 399c-4b50 ┆ 0         ┆ 5         │
│            ┆ 6e4-c97be3 ┆            ┆ -8a0f-ac2 ┆           ┆ -a220-926 ┆           ┆ 08:40:10  │
│            ┆ …          ┆            ┆ b06…      ┆           ┆ 042…      ┆           ┆           │
│ Teen       ┆ a63a5c27-a ┆ i will be  ┆ 2559fbc2- ┆ the same  ┆ 9e193cae- ┆ 165598548 ┆ 2022-06-2 │
│ Suicide    ┆ ae4-40b3-8 ┆ my own     ┆ 0b36-48aa ┆ things    ┆ 5f5a-42af ┆ 2         ┆ 3         │
│            ┆ 6c7-527496 ┆ hell       ┆ -a2fd-1b3 ┆ happening ┆ -adfd-959 ┆           ┆ 11:58:02  │
│            ┆ …          ┆ because …  ┆ 6eb…      ┆ to m…     ┆ 024…      ┆           ┆           │
│ Mitski     ┆ fa58cf24-0 ┆ The Land   ┆ 65c45a70- ┆ My Love   ┆ b293285f- ┆ 169494125 ┆ 2023-09-1 │
│            ┆ e44-421d-8 ┆ Is Inhospi ┆ b218-46d0 ┆ Mine All  ┆ 5600-4380 ┆ 1         ┆ 7         │
│            ┆ 519-8bf461 ┆ table and  ┆ -8dfc-498 ┆ Mine      ┆ -ae13-792 ┆           ┆ 09:00:51  │
│            ┆ …          ┆ S…         ┆ 3b2…      ┆           ┆ 406…      ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [72]:
df = df.with_columns(
    spotify_track_uri = pl.lit("")
)
cols = df.columns

In [73]:
df = df.select(cols)
spotify_df = spotify_df.select(cols)
df_full = spotify_df.vstack(df).sort(pl.col("date_played_unix"), descending=False)
df_full

shape: (180_542, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ artist_na ┆ artist_mb ┆ album_nam ┆ album_mbi ┆ … ┆ track_mbi ┆ date_play ┆ track_pla ┆ spotify_ │
│ me        ┆ id        ┆ e         ┆ d         ┆   ┆ d         ┆ ed_unix   ┆ yed_utc   ┆ track_ur │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ i        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ i64       ┆ datetime[ ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ μs]       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Far East  ┆           ┆ Free      ┆           ┆ … ┆           ┆ 151350667 ┆ 2017-12-1 ┆ spotify: │
│ Movement  ┆           ┆ Wired     ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ track:5A │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 10:31:16  ┆ yL2kgLtT │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ WEu3qO…  │
│ Far East  ┆           ┆ Free      ┆           ┆ … ┆           ┆ 151350688 ┆ 2017-12-1 ┆ spotify: │
│ Movement  ┆           ┆ Wired     ┆           ┆   ┆           ┆ 7         ┆ 7         ┆ track:3Z │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 10:34:47  ┆ uiIFm9nR │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ nkRz8A…  │
│ Far East  ┆           ┆ Dirty     ┆           ┆ … ┆           ┆ 151350712 ┆ 2017-12-1 ┆ spotify: │
│ Movement  ┆           ┆ Bass      ┆           ┆   ┆           ┆ 5         ┆ 7         ┆ track:6d │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 10:38:45  ┆ pKQiQzZE │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2r9rZV…  │
│ Far East  ┆           ┆ Freal Luv ┆           ┆ … ┆           ┆ 151350731 ┆ 2017-12-1 ┆ spotify: │
│ Movement  ┆           ┆ (feat.    ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ track:00 │
│           ┆           ┆ Chanyeol  ┆           ┆   ┆           ┆           ┆ 10:41:56  ┆ rbUJGbcj │
│           ┆           ┆ & Ti…     ┆           ┆   ┆           ┆           ┆           ┆ w3FW5c…  │
│ Far East  ┆           ┆ Dirty     ┆           ┆ … ┆           ┆ 151350738 ┆ 2017-12-1 ┆ spotify: │
│ Movement  ┆           ┆ Bass      ┆           ┆   ┆           ┆ 1         ┆ 7         ┆ track:4H │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 10:43:01  ┆ Q9gXAtON │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Ks8NCM…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ brakence  ┆           ┆ punk2     ┆ bad4bc48- ┆ … ┆ c0645055- ┆ 177446221 ┆ 2026-03-2 ┆          │
│           ┆           ┆           ┆ 356b-45fe ┆   ┆ 8b90-4e90 ┆ 4         ┆ 5         ┆          │
│           ┆           ┆           ┆ -b8ad-d2b ┆   ┆ -8222-f09 ┆           ┆ 18:10:14  ┆          │
│           ┆           ┆           ┆ 897…      ┆   ┆ b80…      ┆           ┆           ┆          │
│ Maya      ┆           ┆ Syko      ┆           ┆ … ┆           ┆ 177446236 ┆ 2026-03-2 ┆          │
│ Ricci     ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆ 5         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 18:12:42  ┆          │
│ Yeat      ┆ 9e6a6a2f- ┆ Alivë     ┆           ┆ … ┆           ┆ 177446248 ┆ 2026-03-2 ┆          │
│           ┆ f696-4cc0 ┆           ┆           ┆   ┆           ┆ 6         ┆ 5         ┆          │
│           ┆ -87f1-e4f ┆           ┆           ┆   ┆           ┆           ┆ 18:14:46  ┆          │
│           ┆ 712…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lloyd     ┆ d75b3154- ┆ Street    ┆ 55f161cd- ┆ … ┆ 04f476ec- ┆ 177446266 ┆ 2026-03-2 ┆          │
│           ┆ fb27-479b ┆ Love      ┆ e1fb-46f0 ┆   ┆ 18e6-3003 ┆ 9         ┆ 5         ┆          │
│           ┆ -b40b-b1b ┆           ┆ -9b2f-a26 ┆   ┆ -8b0b-5d3 ┆           ┆ 18:17:49  ┆          │
│           ┆ 718…      ┆           ┆ 578…      ┆   ┆ d4c…      ┆           ┆           ┆          │
│ Andrew    ┆ 8a0c3a4f- ┆ crown     ┆ 3556324c- ┆ … ┆           ┆ 177446343 ┆ 2026-03-2 ┆          │
│ Aged      ┆ 8115-4261 ┆           ┆ 7380-40b9 ┆   ┆           ┆ 2         ┆ 5         ┆          │
│           ┆ -9f42-30b ┆           ┆ -b6e6-2f1 ┆   ┆           ┆           ┆ 18:30:32  ┆          │
│           ┆ 660…      ┆           ┆ 722…      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [94]:
df_full.null_count()

shape: (1, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ artist_na ┆ artist_mb ┆ album_nam ┆ album_mbi ┆ … ┆ track_mbi ┆ date_play ┆ track_pla ┆ spotify_ │
│ me        ┆ id        ┆ e         ┆ d         ┆   ┆ d         ┆ ed_unix   ┆ yed_utc   ┆ track_ur │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ i        │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 17        ┆ 0         ┆ 17        ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [95]:
df_full.filter(pl.col("artist_name").is_not_null())

shape: (180_525, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ artist_na ┆ artist_mb ┆ album_nam ┆ album_mbi ┆ … ┆ track_mbi ┆ date_play ┆ track_pla ┆ spotify_ │
│ me        ┆ id        ┆ e         ┆ d         ┆   ┆ d         ┆ ed_unix   ┆ yed_utc   ┆ track_ur │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ i        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ i64       ┆ datetime[ ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ μs]       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Far East  ┆           ┆ Free      ┆           ┆ … ┆           ┆ 151350667 ┆ 2017-12-1 ┆ spotify: │
│ Movement  ┆           ┆ Wired     ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ track:5A │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 10:31:16  ┆ yL2kgLtT │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ WEu3qO…  │
│ Far East  ┆           ┆ Free      ┆           ┆ … ┆           ┆ 151350688 ┆ 2017-12-1 ┆ spotify: │
│ Movement  ┆           ┆ Wired     ┆           ┆   ┆           ┆ 7         ┆ 7         ┆ track:3Z │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 10:34:47  ┆ uiIFm9nR │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ nkRz8A…  │
│ Far East  ┆           ┆ Dirty     ┆           ┆ … ┆           ┆ 151350712 ┆ 2017-12-1 ┆ spotify: │
│ Movement  ┆           ┆ Bass      ┆           ┆   ┆           ┆ 5         ┆ 7         ┆ track:6d │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 10:38:45  ┆ pKQiQzZE │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2r9rZV…  │
│ Far East  ┆           ┆ Freal Luv ┆           ┆ … ┆           ┆ 151350731 ┆ 2017-12-1 ┆ spotify: │
│ Movement  ┆           ┆ (feat.    ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ track:00 │
│           ┆           ┆ Chanyeol  ┆           ┆   ┆           ┆           ┆ 10:41:56  ┆ rbUJGbcj │
│           ┆           ┆ & Ti…     ┆           ┆   ┆           ┆           ┆           ┆ w3FW5c…  │
│ Far East  ┆           ┆ Dirty     ┆           ┆ … ┆           ┆ 151350738 ┆ 2017-12-1 ┆ spotify: │
│ Movement  ┆           ┆ Bass      ┆           ┆   ┆           ┆ 1         ┆ 7         ┆ track:4H │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 10:43:01  ┆ Q9gXAtON │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Ks8NCM…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ brakence  ┆           ┆ punk2     ┆ bad4bc48- ┆ … ┆ c0645055- ┆ 177446221 ┆ 2026-03-2 ┆          │
│           ┆           ┆           ┆ 356b-45fe ┆   ┆ 8b90-4e90 ┆ 4         ┆ 5         ┆          │
│           ┆           ┆           ┆ -b8ad-d2b ┆   ┆ -8222-f09 ┆           ┆ 18:10:14  ┆          │
│           ┆           ┆           ┆ 897…      ┆   ┆ b80…      ┆           ┆           ┆          │
│ Maya      ┆           ┆ Syko      ┆           ┆ … ┆           ┆ 177446236 ┆ 2026-03-2 ┆          │
│ Ricci     ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆ 5         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 18:12:42  ┆          │
│ Yeat      ┆ 9e6a6a2f- ┆ Alivë     ┆           ┆ … ┆           ┆ 177446248 ┆ 2026-03-2 ┆          │
│           ┆ f696-4cc0 ┆           ┆           ┆   ┆           ┆ 6         ┆ 5         ┆          │
│           ┆ -87f1-e4f ┆           ┆           ┆   ┆           ┆           ┆ 18:14:46  ┆          │
│           ┆ 712…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lloyd     ┆ d75b3154- ┆ Street    ┆ 55f161cd- ┆ … ┆ 04f476ec- ┆ 177446266 ┆ 2026-03-2 ┆          │
│           ┆ fb27-479b ┆ Love      ┆ e1fb-46f0 ┆   ┆ 18e6-3003 ┆ 9         ┆ 5         ┆          │
│           ┆ -b40b-b1b ┆           ┆ -9b2f-a26 ┆   ┆ -8b0b-5d3 ┆           ┆ 18:17:49  ┆          │
│           ┆ 718…      ┆           ┆ 578…      ┆   ┆ d4c…      ┆           ┆           ┆          │
│ Andrew    ┆ 8a0c3a4f- ┆ crown     ┆ 3556324c- ┆ … ┆           ┆ 177446343 ┆ 2026-03-2 ┆          │
│ Aged      ┆ 8115-4261 ┆           ┆ 7380-40b9 ┆   ┆           ┆ 2         ┆ 5         ┆          │
│           ┆ -9f42-30b ┆           ┆ -b6e6-2f1 ┆   ┆           ┆           ┆ 18:30:32  ┆          │
│           ┆ 660…      ┆           ┆ 722…      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘